package main

import (
	"fmt"
	"os"
	"runtime"
)

func main() {
	fmt.Println("VryEngine Builder v1.0")

	// 1. اكتشاف نظام التشغيل تلقائياً
	osType := runtime.GOOS
	fmt.Printf("Detected OS: %s\n", osType)

	// 2. إنشاء ملف C++ Header يخبر المحرك بنوع النظام
	configFile, err := os.Create("VryConfig.h")
	if err != nil {
		fmt.Println("Error creating config file:", err)
		return
	}
	defer configFile.Close()

	// 3. كتابة التعريفات بناءً على النظام
	configFile.WriteString("// Generated by VryEngine Go Tool\n#pragma once\n\n")
	switch osType {
	case "windows":
		configFile.WriteString("#define VRY_PLATFORM_WINDOWS\n")
	case "darwin":
		configFile.WriteString("#define VRY_PLATFORM_MACOS\n")
	default:
		configFile.WriteString("#define VRY_PLATFORM_LINUX\n")
	}

	fmt.Println("VryConfig.h has been generated successfully.")
}
